-- Messenger App — Database Schema
-- Current schema as of V9 migration (all Flyway migrations V1–V9 merged).
-- Хранимых процедур и триггеров нет — вся бизнес-логика на уровне Java/Spring.

-- ──────────────────────────────────────────────
-- Users & sessions
-- ──────────────────────────────────────────────

create table app_users (
    id                    uuid primary key,
    username              varchar(24)  not null unique,
    email                 varchar(320) not null unique,
    display_name          varchar(40)  not null unique,
    profession            varchar(160),
    avatar_url            text,
    password_hash         varchar(255) not null,
    password_version      bigint       not null default 1,
    mail_enabled          boolean      not null default true,  -- V4
    created_at            timestamp with time zone not null,
    email_verified_at     timestamp with time zone
);

create table user_sessions (
    id           uuid primary key,
    user_id      uuid not null references app_users(id) on delete cascade,
    token_hash   varchar(64)  not null,
    device_name  varchar(160) not null,
    created_at   timestamp with time zone not null,
    last_used_at timestamp with time zone not null,
    expires_at   timestamp with time zone not null,
    revoked_at   timestamp with time zone
);

create index idx_user_sessions_user_id   on user_sessions (user_id);
create index idx_user_sessions_expires_at on user_sessions (expires_at);

-- ──────────────────────────────────────────────
-- Chats
-- ──────────────────────────────────────────────

create table chat_rooms (
    id                             uuid primary key,
    title                          varchar(255),
    is_direct                      boolean not null,
    avatar_url                     text,
    owner_user_id                  uuid references app_users(id) on delete set null,
    direct_user_low_id             uuid references app_users(id) on delete cascade,
    direct_user_high_id            uuid references app_users(id) on delete cascade,
    prejoin_history_policy         varchar(24) not null default 'FULL_HISTORY',
    membership_version             bigint      not null default 0,
    pinned_message_id              uuid,   -- legacy single-pin; superseded by chat_pinned_messages
    pinned_at                      timestamp with time zone,
    created_at                     timestamp with time zone not null,
    constraint chk_chat_rooms_prejoin_history_policy
        check (prejoin_history_policy in ('JOIN_ONLY', 'FULL_HISTORY')),
    constraint chk_chat_rooms_direct_pair
        check (
            (direct_user_low_id is null and direct_user_high_id is null)
            or (
                is_direct = true
                and direct_user_low_id  is not null
                and direct_user_high_id is not null
                and direct_user_low_id <> direct_user_high_id
            )
        ),
    constraint uk_chat_rooms_direct_pair unique (direct_user_low_id, direct_user_high_id)
);

create table chat_participants (
    id                              uuid primary key,
    chat_id                         uuid not null references chat_rooms(id) on delete cascade,
    user_id                         uuid not null references app_users(id) on delete cascade,
    joined_at                       timestamp with time zone not null,
    left_at                         timestamp with time zone,  -- V6
    prejoin_history_access_granted_at timestamp with time zone,
    constraint uk_chat_participants_chat_user unique (chat_id, user_id)
);

create index idx_chat_participants_user_id        on chat_participants (user_id);
create index idx_chat_participants_chat_id_left_at on chat_participants (chat_id, left_at, joined_at);  -- V6

-- ──────────────────────────────────────────────
-- Messages
-- ──────────────────────────────────────────────

create table chat_messages (
    id                        uuid primary key,
    chat_id                   uuid not null references chat_rooms(id) on delete cascade,
    sender_id                 uuid not null references app_users(id) on delete cascade,
    content_ciphertext        bytea       not null,
    content_iv                bytea       not null,
    content_key_version       integer     not null,
    content_algorithm         varchar(32) not null,
    client_message_id         varchar(120),
    server_order              bigint generated by default as identity not null,
    reply_to_message_id       uuid references chat_messages(id) on delete set null,
    forwarded_at              timestamp with time zone,                                          -- V7
    forwarded_from_sender_id  uuid references app_users(id) on delete set null,                 -- V7
    edited_at                 timestamp with time zone,
    created_at                timestamp with time zone not null,
    constraint uk_chat_messages_sender_client_message unique (chat_id, sender_id, client_message_id),
    constraint uk_chat_messages_server_order           unique (server_order)
);

alter table chat_rooms
    add constraint fk_chat_rooms_pinned_message
        foreign key (pinned_message_id)
        references chat_messages(id)
        on delete set null;

create index idx_chat_messages_chat_id_created_at_id    on chat_messages (chat_id, created_at, id);
create index idx_chat_messages_chat_id_server_order     on chat_messages (chat_id, server_order);
create index idx_chat_messages_forwarded_from_sender_id on chat_messages (forwarded_from_sender_id);  -- V7

create table chat_message_keys (
    id             uuid primary key,
    chat_id        uuid    not null references chat_rooms(id) on delete cascade,
    key_version    integer not null,
    encrypted_dek  bytea   not null,
    key_provider   varchar(32)  not null,
    key_reference  varchar(255) not null,
    created_at     timestamp with time zone not null,
    constraint uk_chat_message_keys_chat_version unique (chat_id, key_version)
);

create index idx_chat_message_keys_chat_id_version on chat_message_keys (chat_id, key_version desc);

create table chat_message_links (  -- V3
    id             uuid primary key,
    chat_id        uuid    not null references chat_rooms(id) on delete cascade,
    message_id     uuid    not null references chat_messages(id) on delete cascade,
    url            varchar(2048) not null,
    position_index integer not null,
    created_at     timestamp with time zone not null,
    constraint uk_chat_message_links_message_position unique (message_id, position_index)
);

create index idx_chat_message_links_chat_message_position
    on chat_message_links (chat_id, message_id, position_index);

create table chat_pinned_messages (  -- V5
    id         uuid primary key,
    chat_id    uuid not null references chat_rooms(id)    on delete cascade,
    message_id uuid not null references chat_messages(id) on delete cascade,
    pinned_at  timestamp with time zone not null,
    constraint uk_chat_pinned_messages_chat_message unique (chat_id, message_id)
);

create index ix_chat_pinned_messages_chat_pinned_at
    on chat_pinned_messages (chat_id, pinned_at desc, id desc);

-- ──────────────────────────────────────────────
-- Receipts & reactions
-- ──────────────────────────────────────────────

create table message_receipts (
    id           uuid primary key,
    message_id   uuid not null references chat_messages(id) on delete cascade,
    user_id      uuid not null references app_users(id)     on delete cascade,
    delivered_at timestamp with time zone,
    read_at      timestamp with time zone,
    constraint uk_message_receipts_message_user unique (message_id, user_id),
    constraint chk_message_receipts_read_requires_delivery
        check (read_at is null or delivered_at is not null)
);

create index idx_message_receipts_message_id on message_receipts (message_id);
create index idx_message_receipts_user_id    on message_receipts (user_id);

create table message_reactions (
    id           uuid primary key,
    message_id   uuid        not null references chat_messages(id) on delete cascade,
    user_id      uuid        not null references app_users(id)     on delete cascade,
    reaction_key varchar(24) not null,
    created_at   timestamp with time zone not null,
    constraint uk_message_reactions_message_user_key unique (message_id, user_id, reaction_key)
);

create index idx_message_reactions_message_id on message_reactions (message_id);

create table user_chat_reaction_attentions (  -- V7
    id         uuid primary key,
    user_id    uuid not null references app_users(id)   on delete cascade,
    chat_id    uuid not null references chat_rooms(id)  on delete cascade,
    updated_at timestamp with time zone not null,
    constraint uk_user_chat_reaction_attentions_user_chat unique (user_id, chat_id)
);

create index idx_user_chat_reaction_attentions_user_chat
    on user_chat_reaction_attentions (user_id, chat_id);

-- ──────────────────────────────────────────────
-- User preferences & state
-- ──────────────────────────────────────────────

create table user_deleted_messages (
    id         uuid primary key,
    user_id    uuid not null references app_users(id)     on delete cascade,
    message_id uuid not null references chat_messages(id) on delete cascade,
    deleted_at timestamp with time zone not null,
    constraint uk_user_deleted_messages_user_message unique (user_id, message_id)
);

create index idx_user_deleted_messages_user_id    on user_deleted_messages (user_id);
create index idx_user_deleted_messages_message_id on user_deleted_messages (message_id);

create table user_contacts (
    id              uuid primary key,
    user_id         uuid not null references app_users(id) on delete cascade,
    contact_user_id uuid not null references app_users(id) on delete cascade,
    created_at      timestamp with time zone not null,
    constraint uk_user_contacts_user_contact unique (user_id, contact_user_id),
    constraint chk_user_contacts_not_self check (user_id <> contact_user_id)
);

create index idx_user_contacts_user_id_created_at on user_contacts (user_id, created_at);

create table user_archived_chats (
    id          uuid primary key,
    user_id     uuid not null references app_users(id)  on delete cascade,
    chat_id     uuid not null references chat_rooms(id) on delete cascade,
    archived_at timestamp with time zone not null,
    constraint uk_user_archived_chats_user_chat unique (user_id, chat_id)
);

create index idx_user_archived_chats_user_id_archived_at on user_archived_chats (user_id, archived_at);

create table user_deleted_chats (
    id         uuid primary key,
    user_id    uuid not null references app_users(id)  on delete cascade,
    chat_id    uuid not null references chat_rooms(id) on delete cascade,
    deleted_at timestamp with time zone not null,
    constraint uk_user_deleted_chats_user_chat unique (user_id, chat_id)
);

create index idx_user_deleted_chats_user_id_deleted_at on user_deleted_chats (user_id, deleted_at);

create table user_chat_drafts (
    id         uuid primary key,
    user_id    uuid not null references app_users(id)  on delete cascade,
    chat_id    uuid not null references chat_rooms(id) on delete cascade,
    content    text not null,
    updated_at timestamp with time zone not null,
    constraint uk_user_chat_drafts_user_chat unique (user_id, chat_id)
);

create index idx_user_chat_drafts_user_id_updated_at on user_chat_drafts (user_id, updated_at desc);

create table user_blocks (
    id              uuid primary key,
    user_id         uuid not null references app_users(id) on delete cascade,
    blocked_user_id uuid not null references app_users(id) on delete cascade,
    created_at      timestamp with time zone not null,
    constraint uk_user_blocks_user_blocked_user unique (user_id, blocked_user_id)
);

create index idx_user_blocks_user_id on user_blocks (user_id);

-- ──────────────────────────────────────────────
-- Outbox & pending messages
-- ──────────────────────────────────────────────

create table user_pending_outgoing_messages (
    id                        uuid primary key,
    user_id                   uuid        not null references app_users(id)  on delete cascade,
    chat_id                   uuid        not null references chat_rooms(id) on delete cascade,
    client_message_id         varchar(120) not null,
    content                   text        not null,
    created_at                timestamp with time zone not null,
    local_order               bigint,
    recipient_count           integer     not null,
    reply_to_payload_json     text,
    status                    varchar(24) not null,
    attachments_payload_json  text        not null,
    forwarded_from_message_id uuid,                    -- V8
    updated_at                timestamp with time zone not null,
    constraint chk_user_pending_outgoing_messages_status
        check (status in ('SENDING', 'FAILED')),
    constraint uk_user_pending_outgoing_messages_user_client unique (user_id, client_message_id)
);

create index idx_user_pending_outgoing_messages_user_created_at
    on user_pending_outgoing_messages (user_id, created_at, updated_at);

create table message_dispatch_outbox (
    id               uuid primary key,
    chat_id          uuid        not null,
    message_id       uuid        not null references chat_messages(id) on delete cascade,
    client_message_id varchar(255),
    dispatch_mode    varchar(32) not null,
    attempt_count    integer     not null default 0,
    available_at     timestamp with time zone not null,
    processed_at     timestamp with time zone,
    created_at       timestamp with time zone not null,
    last_error       varchar(2000),
    constraint chk_message_dispatch_outbox_mode
        check (dispatch_mode in ('FULL', 'ACK_ONLY'))
);

create index idx_message_dispatch_outbox_due
    on message_dispatch_outbox (processed_at, available_at, created_at);

-- ──────────────────────────────────────────────
-- Moderation
-- ──────────────────────────────────────────────

create table chat_room_bans (
    id                  uuid primary key,
    chat_id             uuid not null references chat_rooms(id) on delete cascade,
    user_id             uuid not null references app_users(id)  on delete cascade,
    created_by_user_id  uuid not null references app_users(id)  on delete cascade,
    created_at          timestamp with time zone not null,
    constraint uk_chat_room_bans_chat_user unique (chat_id, user_id)
);

create index idx_chat_room_bans_chat_id on chat_room_bans (chat_id);

create table chat_room_moderators (
    id                  uuid primary key,
    chat_id             uuid not null references chat_rooms(id) on delete cascade,
    user_id             uuid not null references app_users(id)  on delete cascade,
    created_by_user_id  uuid not null references app_users(id)  on delete cascade,
    created_at          timestamp with time zone not null,
    constraint uk_chat_room_moderators_chat_user unique (chat_id, user_id)
);

create index idx_chat_room_moderators_chat_id on chat_room_moderators (chat_id);

-- ──────────────────────────────────────────────
-- Invites
-- ──────────────────────────────────────────────

create table invite_links (
    id          uuid primary key,
    code        varchar(16)  not null unique,
    target_type varchar(24)  not null,
    target_id   uuid         not null,
    created_at  timestamp with time zone not null,
    constraint chk_invite_links_target_type
        check (target_type in ('GROUP', 'CONFERENCE')),
    constraint uk_invite_links_target unique (target_type, target_id)
);

create index idx_invite_links_target on invite_links (target_type, target_id);

-- ──────────────────────────────────────────────
-- Video conferences
-- ──────────────────────────────────────────────

create table video_conferences (
    id                  uuid primary key,
    title               varchar(120) not null,
    room_name           varchar(180) unique,
    chat_id             uuid references chat_rooms(id) on delete cascade,  -- V2
    created_by_user_id  uuid not null references app_users(id) on delete cascade,
    scheduled_at        timestamp with time zone not null,
    created_at          timestamp with time zone not null,
    activated_at        timestamp with time zone,
    started_at          timestamp with time zone,
    ended_at            timestamp with time zone
);

create index idx_video_conferences_scheduled_at   on video_conferences (scheduled_at);
create index idx_video_conferences_activated_at   on video_conferences (activated_at);
create index idx_video_conferences_ended_at        on video_conferences (ended_at);
create index idx_video_conferences_chat_id         on video_conferences (chat_id);              -- V2
create index idx_video_conferences_chat_active     on video_conferences (chat_id, ended_at, started_at);  -- V2

create table video_conference_participants (
    id            uuid primary key,
    conference_id uuid not null references video_conferences(id) on delete cascade,
    user_id       uuid not null references app_users(id)         on delete cascade,
    invited_at    timestamp with time zone not null,
    constraint uk_video_conference_participants_conference_user unique (conference_id, user_id)
);

create index idx_video_conference_participants_user_id        on video_conference_participants (user_id);
create index idx_video_conference_participants_conference_id  on video_conference_participants (conference_id);

create table video_conference_attendance (
    id            uuid primary key,
    conference_id uuid not null references video_conferences(id) on delete cascade,
    user_id       uuid not null references app_users(id)          on delete cascade,
    session_id    uuid not null references user_sessions(id)      on delete cascade,
    joined_at     timestamp with time zone not null,
    last_seen_at  timestamp with time zone not null,
    left_at       timestamp with time zone,
    constraint uk_video_conference_attendance_conference_session unique (conference_id, session_id)
);

create index idx_video_conference_attendance_conference_active
    on video_conference_attendance (conference_id, left_at, last_seen_at);
create index idx_video_conference_attendance_session_id
    on video_conference_attendance (session_id);

create table conference_recordings (
    conference_id      uuid primary key references video_conferences(id) on delete cascade,
    stored_filename    varchar(220) not null,
    mime_type          varchar(120) not null,
    size_bytes         bigint       not null,
    created_at         timestamp with time zone not null,
    uploaded_by_user_id uuid not null references app_users(id) on delete cascade
);

-- ──────────────────────────────────────────────
-- Attachments
-- ──────────────────────────────────────────────

create table chat_attachments (
    id           uuid primary key,
    chat_id      uuid not null references chat_rooms(id)    on delete cascade,
    message_id   uuid          references chat_messages(id) on delete set null,
    uploader_id  uuid not null references app_users(id)     on delete cascade,
    storage_key  varchar(255) not null unique,
    file_name    varchar(255) not null,
    mime_type    varchar(255) not null,
    size_bytes   bigint       not null,
    created_at   timestamp with time zone not null,
    constraint chk_chat_attachments_size_positive check (size_bytes > 0)
);

create index idx_chat_attachments_chat_created_at    on chat_attachments (chat_id, created_at);
create index idx_chat_attachments_message_id         on chat_attachments (message_id);
create index idx_chat_attachments_uploader_created_at on chat_attachments (uploader_id, created_at);

-- ──────────────────────────────────────────────
-- Push notifications
-- ──────────────────────────────────────────────

create table user_push_subscriptions (
    id               uuid primary key,
    user_id          uuid         not null references app_users(id) on delete cascade,
    endpoint         varchar(2048) not null unique,
    p256dh           varchar(512) not null,
    auth             varchar(256) not null,
    expiration_time  timestamp with time zone,
    user_agent       varchar(512),
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null
);

create index idx_user_push_subscriptions_user_updated_at
    on user_push_subscriptions (user_id, updated_at);

-- ──────────────────────────────────────────────
-- Mail
-- ──────────────────────────────────────────────

create table user_mailboxes (  -- V4
    id         uuid primary key,
    user_id    uuid         not null references app_users(id) on delete cascade,
    email      varchar(320) not null,
    created_at timestamp with time zone not null,
    constraint uk_user_mailboxes_user_email unique (user_id, email)
);

create index idx_user_mailboxes_user_created_at
    on user_mailboxes (user_id, created_at desc);

-- ──────────────────────────────────────────────
-- Auth tokens
-- ──────────────────────────────────────────────

create table password_reset_tokens (
    id         uuid primary key,
    user_id    uuid        not null references app_users(id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    used_at    timestamp with time zone
);

create index idx_password_reset_tokens_user_id    on password_reset_tokens (user_id);
create index idx_password_reset_tokens_expires_at on password_reset_tokens (expires_at);

create table email_verification_tokens (
    id         uuid primary key,
    user_id    uuid        not null references app_users(id) on delete cascade,
    token_hash varchar(64) not null unique,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    used_at    timestamp with time zone
);

create index idx_email_verification_tokens_user_id    on email_verification_tokens (user_id);
create index idx_email_verification_tokens_expires_at on email_verification_tokens (expires_at);

create table email_change_tokens (  -- V9
    id            uuid primary key,
    user_id       uuid         not null references app_users(id) on delete cascade,
    pending_email varchar(320) not null,
    token_hash    varchar(64)  not null,
    created_at    timestamp with time zone not null,
    expires_at    timestamp with time zone not null,
    used_at       timestamp with time zone
);

create index idx_email_change_tokens_user_id    on email_change_tokens (user_id);
create index idx_email_change_tokens_token_hash on email_change_tokens (token_hash);
